name: jp_app_final
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_inset_box_shadow_update: ^0.0.1
  google_fonts: ^6.3.0
  gradient_borders: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/burger.png
    - assets/images/cupcake_chick.png
    - assets/images/cupcake_cat.png
    - assets/images/icecream_cone.png
    - assets/images/icecream_stick.png
    - assets/images/icecream.png
    - assets/images/star.png

    - assets/backgrounds/bg_mainscreen.png
    - assets/backgrounds/bg_startscreen.png

    - assets/details/cut_card.png
    - assets/details/snack_snack.png
    - assets/details/cut_card_shiny.png

    - assets/icons/currency.png
    - assets/icons/lunch.png

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro/SF-Pro-Italic.ttf
          style: italic
        - asset: assets/fonts/SF-Pro/SF-Pro-Text-Regular.otf
          style: normal
        - asset: assets/fonts/SF-Pro/SF-Pro-Display-Semibold.otf
          style: normal
